version: '3'

services:
  gp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: graph-positioning
    container_name: graph-positioning
    ports:
    - "5000:5000"
    restart: unless-stopped